### ISSUE TITLE
support for PutKeyPolicy?

### ISSUE THREAD

**Issue by shb7628** [nsmithuk/local-kms#12]
do you anticipate support for PutKeyPolicy?

**Comment by nsmithuk** [comment]
Hi @shb7628 

The short answer is yes; at least to the extent of being able to pass a string to `Policy`, which can then be returned via `GetKeyPolicy`.

I haven't put too much thought yet into what extent, if any, I'd go to mocking the validation of the passed string (policy).

Can you tell me what specific user-case you're aiming to mock using that endpoint, and I'll have a think about what would be involved?

**Comment by bryanlalexander** [comment]
@nsmithuk We are interested in this feature as well, and would be willing to implement it (as you described it, store a string, retrieve a string). Our particular use-case is specifically relating to testing terraform code using localstack.

**Comment by nsmithuk** [comment]
Hi @bryanlalexander & @shb7628 

Support for PutKeyPolicy has been added in v3.3.0. As discussed above, `Policy` will accept any non-empty string. That same string can then be returned via GetKeyPolicy.

Please give it a test and let me know if it meets your use-cases.

A note on localstack, I believe they're pulling a pre-build binary, thus a fixed version of local-kms. I'll take a look now to see what's involved in always pulling in the latest version (locked to 3.*).

**Comment by nsmithuk** [comment]
I've added a PR for localstack to ensure they're always pulling in the latest tag of v3: https://github.com/localstack/localstack/pull/1923
