### ISSUE TITLE
Implement seeding of Asymmetric Keys 

### ISSUE THREAD

**Issue by mjeffrey** [nsmithuk/local-kms#25]
Hi 

We have a requirement for stable asymmetric keys for signing. I have created a PR for it.

[Pull request](https://github.com/nsmithuk/local-kms/pull/26)

There is a bit of duplication in the code which could be improved by someone with more experience.
I'm pretty new to Go I only started today and this is my first code 😄 .

The existing code was very easy to follow and logically structured which made it really easy.

Notes: 
I have only coded this, no tests, no docs. If you think the approach is OK I can do the docs.
There is a bash script for generating some YAML for the seed (I can put this in docs). 

p.s. thanks for a great product. It really helps us out in development and testing (we are using local KMS in localstack)

**Comment by mjeffrey** [comment]
I have improved my Go skills and removed most of the duplication but won't make a PR yet.
I just want to check that what I have done is OK in principle. 

cheers
Mark

**Comment by nsmithuk** [comment]
Hi @mjeffrey. Thank you for doing that. I'll take a look over the next couple of days. 🙂

**Comment by nsmithuk** [comment]
Hi @mjeffrey. It looks great - definitely the right direction. I've added one small tweak onto your PR.

**Comment by nsmithuk** [comment]
Hi @mjeffrey 

Your PR has been merged and tagged as 3.9.0. All localstack builds done as of now should pull in that new version.

Thank you for contributing the feature 🙂
