### ISSUE TITLE
Refactoring switch case 

### ISSUE THREAD

**Issue by GuilhermeFirmiano** [nsmithuk/local-kms#3]
You could use reflection

**Comment by GuilhermeFirmiano** [comment]
`w.Header().Set("Content-Type", "application/x-amz-json-1.1")

		h := handler.NewRequestHandler(r, logger, database)

		split := strings.Split(r.Header.Get("X-Amz-Target"), ".")

		method := reflect.ValueOf(h).MethodByName(split[1])

		if method.IsValid() {
			result := method.Call([]reflect.Value{})

			response := result[0].Interface().(handler.Response)

			respond(w, response)
		}

		error501(w)`

**Comment by nsmithuk** [comment]
Thank you for the feedback @GuilhermeFirmiano. You're right, that switch statement is a little unwieldy. I'll take a look over at what you're suggesting.

**Comment by nsmithuk** [comment]
Hi @GuilhermeFirmiano. Thank you again for the feedback. I've just pushed the change.
