### ISSUE TITLE
Return KeySpec instead of CustomerMasterKeySpec

### ISSUE THREAD

**Issue by doris-yolabs** [nsmithuk/local-kms#32]
`CustomerMasterKeySpec` is deprecated in favor of just `KeySpec`.  According to https://docs.aws.amazon.com/kms/latest/developerguide/symm-asymm-choose.html, `the response of the CreateKey and DescribeKey operations includes a KeySpec and CustomerMasterKeySpec member with the same value.`

LocalKMS should update the two operations to recognize/return `KeySpec` as well.

**Comment by nsmithuk** [comment]
Hi @doris-yolabs Thank you for raising this. As I can see you have seen, this has been fixed in the latest release.
