### ISSUE TITLE
can you allow this to support ssl?

### ISSUE THREAD

**Issue by dmohnen** [nsmithuk/local-kms#39]
Trying to use this to test with the AWS encryption sdk and they only use SSL to make the calls.

**Comment by nsmithuk** [comment]
Hi @dmohnen. Are you running local-kms in docker? If so I'd typically run a TLS reverse proxy container to do something like this. I'm happy to put an example together if that would be helpful?

**Comment by dmohnen** [comment]
Neil thanks for that I did that and it worked.  Thanks.
