### ISSUE TITLE
Update go version

### ISSUE THREAD

**Issue by notthepoint** [nsmithuk/local-kms#45]
Could you publish a new version of your docker image? 
It's currently using 1.17.9, which contains several CVEs. The CVEs would be solved by using 1.17.13.

**Comment by nsmithuk** [comment]
Hi @notthepoint

Thank you for pointing this out! :-)

I re-triggered the build for this; it should now have been built with the latest version of 1.17.

I'll look at moving to 1.19 at some point, but unfortunately Go have changed how the NIST curves are stored internally, which will mean a refactor on the local-kms side before it can be upgraded.

**Comment by notthepoint** [comment]
Thank you!
