### ISSUE TITLE
Push image to AWS ECR

### ISSUE THREAD

**Issue by tenjaa** [nsmithuk/local-kms#63]
Hi,

I would love to see this docker image in the public AWS registry too.
https://gallery.ecr.aws/

I think the biggest benefit would be, to not be dependent on the rate limiting and a lot of users would probably run in it AWS anyway

**Comment by nsmithuk** [comment]
Hello

Yes, can do. Just waiting for https://github.com/wbond/oscrypto/issues/78 to be resolved (which has broken my automated tests), but once done I'll start pushing to ECR public.

**Comment by nsmithuk** [comment]
Hello @tenjaa 

This is done. You have:
```
public.ecr.aws/nsmithuk/local-kms:3.11.7
public.ecr.aws/nsmithuk/local-kms:3
public.ecr.aws/nsmithuk/local-kms:latest
```
