### ISSUE TITLE
Missing TrentService.GetKeyPolicy for Terraform.

### ISSUE THREAD

**Issue by wesselvdv** [nsmithuk/local-kms#9]
Seems this local implementation is missing TrentService.GetKeyPolicy for Terraform. I am able to deploy a kms key locally using this lib, but refreshing the state seems to require another route that isn't implemented. I could take a swing at it, see if I can create it myself.

**Comment by nsmithuk** [comment]
Hello @wesselvdv 

Yes, you're right, no endpoints relating to Key Policies have been implemented yet. I've never used that endpoint myself, so I'm not sure how complex it would be to do. Please do go ahead and give it a go though. I'm happy to help where I can.

**Comment by wesselvdv** [comment]
After taking a look at the AWS docs regarding this specific route, it seems I could add a simple 'mock' handler that will always return the name `default` as the key policy. Which is actually correct since the `TrentService.CreateKey` handler in this local implementation doesn't support the `Policy` property.

Another approach could be to add the put and get variants of KeyPolicy, and add the `Policy` property which would at least make sure that if given a custom policy it could return the correct custom one.

**Comment by nsmithuk** [comment]
@wesselvdv Thank you for your contribution on this.

It's merged in and available under the following tags:
- 3.1.0
- 3
- latest
